# Generated by Django 3.1.7 on 2021-09-11 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filmes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(default=None)),
                ('avaliation', models.FloatField(default=0, null=True, validators=[filmes.validators.validade_if_the_note_is_valid])),
                ('visto', models.BooleanField(default=False)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
