# Generated by Django 3.1.7 on 2021-08-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_auto_20210823_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='avaliation',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
